### ISSUE TITLE
Remove Find API dependence in imageloader

### ISSUE THREAD

**Issue by lastlegion** [camicroscope/Security#28]
Right now we make a check for duplicate images using [find api](https://github.com/SBU-BMI/findapi), this should be possible using the image loader APIs or using bindaas directly. See: https://github.com/camicroscope/Security/blob/release/imageformuploader.php#L164

Right now this dependance makes FindAPI a required part of our distribution. Our goal should be to make it optional for vanilla camicroscope distribution

**Comment by lastlegion** [comment]
we can use the API from image loader: https://github.com/camicroscope/ImageLoader#get-subjectidexists

**Comment by birm** [comment]
solved w/ #31
