### ISSUE TITLE
camicSignup absolute links not working with reverseproxy

### ISSUE THREAD

**Issue by lastlegion** [camicroscope/Security#50]
The camicSignup app links don't work well behind a reverseproxy since it expects absolute paths.

For example (https://github.com/camicroscope/Security/blob/release/camicSignup/index.html#L7)
`/css/bootstrap/css/bootstrap.min.css` should be `../css/bootstrap/css/bootstrap.min.css`
and so on

**Comment by birm** [comment]
On it

**Comment by birm** [comment]
Solved in #51
