### ISSUE TITLE
signup user not working

### ISSUE THREAD

**Issue by tdiprima** [camicroscope/Security#68]
### Branch: develop

When I click the "Signup User" button, it takes me back to the Login screen.
I set the client_id and client_secret in both `config.ini` and `security_config.php`.
Further attempts to sign in send me back to [request.php?doAction=signUp](request.php?doAction=signUp).

**Comment by birm** [comment]
this seems to be due to authenticate.php requiring an active session, which, at least on first sign up, does not exist. I've commented these requires out, but I'm nervous about the security implications of that.

**Comment by ebremer** [comment]
@lastlegion @birm any ETA on a fix(es) for this issue?

**Comment by birm** [comment]
The recent push to develop fixes the core issue, but I'm still concerned about any implications of removing authenticate.php.

**Comment by ebremer** [comment]
What steps are you taking to address your concern?

**Comment by birm** [comment]
After testing, it seems as though the authentication on the camicsignup folder works as intended.

All this change means is that you don't need to be signed into the application to do admin changes (instead only the admin password is required).

**Comment by tdiprima** [comment]
Tested on 177.
Error screen from [camicSignup registerNew](http://tahsin177.informatics.stonybrook.edu/camicSignup/registerNew.php):

<img width="458" alt="screen shot 2018-04-03 at 10 36 09 am" src="https://user-images.githubusercontent.com/4490270/38256108-8b753654-372b-11e8-8405-dc252b14d0ee.png">
